name: CI test build

on:
  push:
      branches:
        - test-*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release
    - name: Publish API
      run: dotnet publish --no-build ./src/Antares.Service.History/Antares.Service.History.csproj --output ./publish-api --configuration Release
    - name: Publish worker
      run: dotnet publish --no-build ./src/Antares.Job.History/Antares.Job.History.csproj --output ./publish-worker --configuration Release
    - name: Check API dir
      run: ls ./publish-api
    - name: Check worker dir
      run: ls ./publish-worker
    - name: Publish API to Registry
      uses: swisschain/Publish-Docker-Github-Action@master
      with:
        name: swisschains/antares-history-api:test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./publish-api
        # snapshot: true # use snapshot to push an additional image, which is tagged with {YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}{first 6 digits of the git sha}
        tag_names: true  
    - name: Publish worker to Registry
      uses: swisschain/Publish-Docker-Github-Action@master
      with:
        name: swisschains/antares-history-job:test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./publish-worker
        # snapshot: true # use snapshot to push an additional image, which is tagged with {YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}{first 6 digits of the git sha}
        tag_names: true  
    - name: Restart service
      uses: swisschain/kube-restart-pods@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.LYKKE_TEST_KUBE_CONFIG_DATA }}
        NAMESPACE: services
        POD: history
    - name: Restart job
      uses: swisschain/kube-restart-pods@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.LYKKE_TEST_KUBE_CONFIG_DATA }}
        NAMESPACE: lykke-jobs
        POD: history-job